-- ============================================
-- ENGLISH LEARNING QUIZ QUESTIONS
-- 6 Categories × 3 Levels × 7 Questions = 126 Questions
-- All content in English
-- Uses WITH cat AS to resolve UUID category_id
-- ============================================

-- ============================================
-- GRAMMAR QUESTIONS
-- ============================================

-- Grammar Easy
WITH cat AS (SELECT id FROM categories WHERE slug = 'grammar')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Which sentence uses the correct present simple tense?', '[{"label": "A", "text": "She go to school every day."}, {"label": "B", "text": "She goes to school every day."}, {"label": "C", "text": "She going to school every day."}, {"label": "D", "text": "She gone to school every day."}]', 'B', 'In present simple, third person singular (she/he/it) requires the verb to end in -s or -es. "She goes" is the correct form.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Choose the correct past tense of "go":', '[{"label": "A", "text": "goed"}, {"label": "B", "text": "went"}, {"label": "C", "text": "goed"}, {"label": "D", "text": "going"}]', 'B', '"Go" is an irregular verb. Its past tense is "went", not "goed".'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Which sentence is in the future tense?', '[{"label": "A", "text": "I am eating dinner now."}, {"label": "B", "text": "I ate dinner yesterday."}, {"label": "C", "text": "I will eat dinner tonight."}, {"label": "D", "text": "I eat dinner every night."}]', 'C', '"Will eat" is the future tense, indicating an action that will happen later.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'What is the correct article? "She is ___ teacher."', '[{"label": "A", "text": "a"}, {"label": "B", "text": "an"}, {"label": "C", "text": "the"}, {"label": "D", "text": "no article needed"}]', 'A', 'Use "a" before words that start with a consonant sound. "Teacher" starts with /t/, so we use "a".'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Which sentence uses the correct form of "be"?', '[{"label": "A", "text": "I is happy."}, {"label": "B", "text": "I am happy."}, {"label": "C", "text": "I are happy."}, {"label": "D", "text": "I be happy."}]', 'B', 'The correct form of "be" for "I" is "am". "I am happy." is correct.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Choose the plural form of "child":', '[{"label": "A", "text": "childs"}, {"label": "B", "text": "childen"}, {"label": "C", "text": "children"}, {"label": "D", "text": "childes"}]', 'C', '"Child" is an irregular noun. Its plural form is "children".'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Which sentence is grammatically correct?', '[{"label": "A", "text": "He don''t like coffee."}, {"label": "B", "text": "He doesn''t like coffee."}, {"label": "C", "text": "He not like coffee."}, {"label": "D", "text": "He no like coffee."}]', 'B', 'For third person singular (he/she/it), we use "does not" or "doesn''t" to form negatives.');

-- Grammar Medium
WITH cat AS (SELECT id FROM categories WHERE slug = 'grammar')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which sentence is in the passive voice?', '[{"label": "A", "text": "The chef cooks the meal."}, {"label": "B", "text": "The meal is cooked by the chef."}, {"label": "C", "text": "The chef is cooking the meal."}, {"label": "D", "text": "The chef has cooked the meal."}]', 'B', 'Passive voice uses "be + past participle" and focuses on the action, not the doer. "The meal is cooked by the chef" is passive.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Complete: "If I ___ rich, I would travel the world."', '[{"label": "A", "text": "am"}, {"label": "B", "text": "was"}, {"label": "C", "text": "were"}, {"label": "D", "text": "will be"}]', 'C', 'This is a second conditional (unreal/hypothetical situation). We use "were" for all subjects in the if-clause.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which sentence uses a modal verb correctly?', '[{"label": "A", "text": "You must to study hard."}, {"label": "B", "text": "You must study hard."}, {"label": "C", "text": "You musts study hard."}, {"label": "D", "text": "You must studying hard."}]', 'B', 'Modal verbs (must, can, should, etc.) are followed by the base form of the verb without "to".'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Choose the correct reported speech: He said, "I am tired."', '[{"label": "A", "text": "He said he is tired."}, {"label": "B", "text": "He said he was tired."}, {"label": "C", "text": "He said I am tired."}, {"label": "D", "text": "He said I was tired."}]', 'B', 'In reported speech, we backshift tenses: present "am" becomes past "was". The pronoun changes from "I" to "he".'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which sentence has the correct subject-verb agreement?', '[{"label": "A", "text": "The group of students are studying."}, {"label": "B", "text": "The group of students is studying."}, {"label": "C", "text": "The group of students were studying."}, {"label": "D", "text": "The group of students have studying."}]', 'B', '"Group" is a collective noun that takes a singular verb. "The group is studying" is correct.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What does "would have done" express?', '[{"label": "A", "text": "Present possibility"}, {"label": "B", "text": "Future intention"}, {"label": "C", "text": "Past unreal condition"}, {"label": "D", "text": "Current habit"}]', 'C', '"Would have done" is the third conditional, expressing a hypothetical action in the past that did not actually happen.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which sentence uses the present perfect correctly?', '[{"label": "A", "text": "I have went to Paris."}, {"label": "B", "text": "I have gone to Paris."}, {"label": "C", "text": "I have go to Paris."}, {"label": "D", "text": "I have going to Paris."}]', 'B', 'Present perfect uses "have/has + past participle". The past participle of "go" is "gone".');

-- Grammar Hard
WITH cat AS (SELECT id FROM categories WHERE slug = 'grammar')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Which sentence contains a dangling modifier?', '[{"label": "A", "text": "After reading the book, the lights went out."}, {"label": "B", "text": "After I read the book, the lights went out."}, {"label": "C", "text": "The lights went out after I read the book."}, {"label": "D", "text": "When I finished reading, the lights went out."}]', 'A', 'A dangling modifier has no clear subject. "After reading" seems to modify "the lights" instead of a person.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Identify the sentence with correct parallel structure:', '[{"label": "A", "text": "She likes swimming, to run, and cycling."}, {"label": "B", "text": "She likes to swim, running, and cycling."}, {"label": "C", "text": "She likes swimming, running, and cycling."}, {"label": "D", "text": "She likes swim, run, and cycle."}]', 'C', 'Parallel structure requires items in a list to be in the same grammatical form: all gerunds (-ing form).'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Which sentence correctly uses the subjunctive mood?', '[{"label": "A", "text": "I wish I was taller."}, {"label": "B", "text": "I wish I were taller."}, {"label": "C", "text": "I wish I am taller."}, {"label": "D", "text": "I wish I will be taller."}]', 'B', 'The subjunctive mood uses "were" for all subjects in hypothetical or wishful statements, even with "I".'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What is the error in: "Neither the teacher nor the students was present."', '[{"label": "A", "text": "Neither should be either"}, {"label": "B", "text": "was should be were"}, {"label": "C", "text": "nor should be or"}, {"label": "D", "text": "No error"}]', 'B', 'With "neither...nor", the verb agrees with the nearest subject. "Students" is plural, so the verb should be "were".'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Which sentence is in the active voice?', '[{"label": "A", "text": "The cake was baked by Mary."}, {"label": "B", "text": "The cake has been baked."}, {"label": "C", "text": "Mary baked the cake."}, {"label": "D", "text": "The cake is being baked."}]', 'C', 'Active voice has the subject performing the action. "Mary baked the cake" has Mary (subject) performing the action (baked).'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Choose the sentence with correct semicolon usage:', '[{"label": "A", "text": "I love coffee; and tea."}, {"label": "B", "text": "I love coffee; tea is my favorite."}, {"label": "C", "text": "I love coffee; because it wakes me up."}, {"label": "D", "text": "I love coffee; however, I prefer tea."}]', 'D', 'Semicolons connect independent clauses. "However" is a conjunctive adverb, so a semicolon before it and comma after is correct.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What does "Had I known" express?', '[{"label": "A", "text": "Past certainty"}, {"label": "B", "text": "Future plan"}, {"label": "C", "text": "Past regret (third conditional inversion)"}, {"label": "D", "text": "Present condition"}]', 'C', '"Had I known" is an inverted third conditional, expressing regret about a past situation that cannot be changed.');

-- ============================================
-- VOCABULARY QUESTIONS
-- ============================================

-- Vocabulary Easy
WITH cat AS (SELECT id FROM categories WHERE slug = 'vocabulary')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'What is the meaning of "happy"?', '[{"label": "A", "text": "Sad"}, {"label": "B", "text": "Joyful"}, {"label": "C", "text": "Angry"}, {"label": "D", "text": "Tired"}]', 'B', '"Happy" means feeling or showing pleasure or contentment. "Joyful" is the closest synonym.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Which word is the opposite of "big"?', '[{"label": "A", "text": "Large"}, {"label": "B", "text": "Huge"}, {"label": "C", "text": "Small"}, {"label": "D", "text": "Giant"}]', 'C', '"Big" and "small" are antonyms. "Big" means large in size, while "small" means little.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Choose the correct word: "She ___ to the store."', '[{"label": "A", "text": "goed"}, {"label": "B", "text": "go"}, {"label": "C", "text": "goes"}, {"label": "D", "text": "going"}]', 'C', '"She" is third person singular, so the verb needs -es: "goes".'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'What does "beautiful" mean?', '[{"label": "A", "text": "Ugly"}, {"label": "B", "text": "Pretty or attractive"}, {"label": "C", "text": "Ugly"}, {"label": "D", "text": "Boring"}]', 'B', '"Beautiful" means pleasing to the senses or mind; aesthetically attractive.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Which word means "a place where you buy things"?', '[{"label": "A", "text": "School"}, {"label": "B", "text": "Hospital"}, {"label": "C", "text": "Store"}, {"label": "D", "text": "Park"}]', 'C', 'A "store" (or shop) is a place where goods are sold to customers.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'What is the plural of "mouse"?', '[{"label": "A", "text": "mouses"}, {"label": "B", "text": "mice"}, {"label": "C", "text": "mouse"}, {"label": "D", "text": "mousies"}]', 'B', '"Mouse" is an irregular noun. Its plural is "mice".'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Choose the synonym for "quickly":', '[{"label": "A", "text": "Slowly"}, {"label": "B", "text": "Fast"}, {"label": "C", "text": "Quickly"}, {"label": "D", "text": "Lazily"}]', 'B', '"Quickly" and "fast" both mean at high speed or with rapidity.');

-- Vocabulary Medium
WITH cat AS (SELECT id FROM categories WHERE slug = 'vocabulary')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What is the meaning of "ambiguous"?', '[{"label": "A", "text": "Clear and definite"}, {"label": "B", "text": "Open to more than one interpretation"}, {"label": "C", "text": "Very angry"}, {"label": "D", "text": "Extremely happy"}]', 'B', '"Ambiguous" means unclear or open to multiple interpretations.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which word is a synonym for "ephemeral"?', '[{"label": "A", "text": "Permanent"}, {"label": "B", "text": "Long-lasting"}, {"label": "C", "text": "Short-lived"}, {"label": "D", "text": "Eternal"}]', 'C', '"Ephemeral" means lasting for a very short time. "Short-lived" is the closest synonym.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What does the prefix "un-" mean in "unhappy"?', '[{"label": "A", "text": "Again"}, {"label": "B", "text": "Not"}, {"label": "C", "text": "Before"}, {"label": "D", "text": "After"}]', 'B', 'The prefix "un-" means "not". "Unhappy" means "not happy".'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Choose the correct word: "The professor gave a ___ on climate change."', '[{"label": "A", "text": "peach"}, {"label": "B", "text": "peech"}, {"label": "C", "text": "speech"}, {"label": "D", "text": "beach"}]', 'C', 'A "speech" is a formal talk given to an audience.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What is the antonym of "generous"?', '[{"label": "A", "text": "Kind"}, {"label": "B", "text": "Giving"}, {"label": "C", "text": "Stingy"}, {"label": "D", "text": "Rich"}]', 'C', '"Generous" means willing to give. Its opposite is "stingy" (unwilling to give).'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which word means "to make something smaller"?', '[{"label": "A", "text": "Expand"}, {"label": "B", "text": "Enlarge"}, {"label": "C", "text": "Reduce"}, {"label": "D", "text": "Increase"}]', 'C', '"Reduce" means to make smaller in size, amount, or degree.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What does "irony" mean?', '[{"label": "A", "text": "Being very serious"}, {"label": "B", "text": "The opposite of what is expected"}, {"label": "C", "text": "Being very funny"}, {"label": "D", "text": "A type of metal"}]', 'B', 'Irony is when the outcome is opposite to what was expected.');

-- Vocabulary Hard
WITH cat AS (SELECT id FROM categories WHERE slug = 'vocabulary')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What is the meaning of "ubiquitous"?', '[{"label": "A", "text": "Rare"}, {"label": "B", "text": "Found everywhere"}, {"label": "C", "text": "Very large"}, {"label": "D", "text": "Extremely small"}]', 'B', '"Ubiquitous" means present, appearing, or found everywhere.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Choose the word that best completes: "Her ___ speech impressed everyone."', '[{"label": "A", "text": "eloquent"}, {"label": "B", "text": "silent"}, {"label": "C", "text": "loud"}, {"label": "D", "text": "boring"}]', 'A', '"Eloquent" means fluent, persuasive, and expressive in speaking or writing.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What does "cacophony" mean?', '[{"label": "A", "text": "Beautiful music"}, {"label": "B", "text": "Harsh, discordant sounds"}, {"label": "C", "text": "Complete silence"}, {"label": "D", "text": "A single voice"}]', 'B', '"Cacophony" refers to a harsh, discordant mixture of sounds.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Which word is a homophone of "their"?', '[{"label": "A", "text": "there"}, {"label": "B", "text": "these"}, {"label": "C", "text": "those"}, {"label": "D", "text": "them"}]', 'A', '"Their" and "there" are homophones (same pronunciation, different meanings). "Their" shows possession; "there" indicates place.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What is the meaning of "pragmatic"?', '[{"label": "A", "text": "Idealistic"}, {"label": "B", "text": "Dealing with things sensibly and realistically"}, {"label": "C", "text": "Very emotional"}, {"label": "D", "text": "Extremely lazy"}]', 'B', '"Pragmatic" means dealing with things sensibly and realistically based on practical considerations.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Choose the correct word: "The scientist made a ___ discovery."', '[{"label": "A", "text": "momento"}, {"label": "B", "text": "momentum"}, {"label": "C", "text": "momentous"}, {"label": "D", "text": "momentary"}]', 'C', '"Momentous" means of great importance or significance. A "momentous discovery" is a significant one.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What does "perfunctory" mean?', '[{"label": "A", "text": "Done with great care"}, {"label": "B", "text": "Carried out with minimum effort"}, {"label": "C", "text": "Extremely enthusiastic"}, {"label": "D", "text": "Very detailed"}]', 'B', '"Perfunctory" means carried out with minimum effort or reflection.');

-- ============================================
-- READING QUESTIONS
-- ============================================

-- Reading Easy
WITH cat AS (SELECT id FROM categories WHERE slug = 'reading')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Read: "The cat sat on the mat." What did the cat do?', '[{"label": "A", "text": "The cat stood."}, {"label": "B", "text": "The cat sat."}, {"label": "C", "text": "The cat ran."}, {"label": "D", "text": "The cat slept."}]', 'B', 'The sentence clearly states "The cat sat on the mat."'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Read: "Mary has two dogs. One is black and one is white." How many dogs does Mary have?', '[{"label": "A", "text": "One"}, {"label": "B", "text": "Two"}, {"label": "C", "text": "Three"}, {"label": "D", "text": "Four"}]', 'B', 'The text explicitly states "Mary has two dogs."'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Read: "Tom woke up early. He brushed his teeth and ate breakfast." What did Tom do first?', '[{"label": "A", "text": "Brushed his teeth"}, {"label": "B", "text": "Ate breakfast"}, {"label": "C", "text": "Woke up"}, {"label": "D", "text": "Went to school"}]', 'C', 'The sequence shows Tom woke up first, then brushed teeth, then ate breakfast.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Read: "The weather was cold, so Sarah wore a jacket." Why did Sarah wear a jacket?', '[{"label": "A", "text": "Because it was hot"}, {"label": "B", "text": "Because it was cold"}, {"label": "C", "text": "Because she was going to a party"}, {"label": "D", "text": "Because her mother told her"}]', 'B', 'The text states "The weather was cold" as the reason for wearing a jacket.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Read: "John likes apples. He eats one every day." How often does John eat apples?', '[{"label": "A", "text": "Once a week"}, {"label": "B", "text": "Every day"}, {"label": "C", "text": "Once a month"}, {"label": "D", "text": "Never"}]', 'B', 'The text says "He eats one every day."'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Read: "The library is open from 9 AM to 5 PM." When does the library close?', '[{"label": "A", "text": "9 AM"}, {"label": "B", "text": "12 PM"}, {"label": "C", "text": "5 PM"}, {"label": "D", "text": "6 PM"}]', 'C', 'The text states the library is open "from 9 AM to 5 PM", so it closes at 5 PM.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Read: "Lisa is taller than her brother." Who is taller?', '[{"label": "A", "text": "Her brother"}, {"label": "B", "text": "Lisa"}, {"label": "C", "text": "They are the same height"}, {"label": "D", "text": "Not mentioned"}]', 'B', 'The text explicitly states "Lisa is taller than her brother."');

-- Reading Medium
WITH cat AS (SELECT id FROM categories WHERE slug = 'reading')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Read: "Despite the rain, the children continued playing outside. They had too much fun to stop." What can you infer about the children?', '[{"label": "A", "text": "They dislike rain"}, {"label": "B", "text": "They were having fun despite the weather"}, {"label": "C", "text": "They were cold"}, {"label": "D", "text": "They wanted to go inside"}]', 'B', 'The text says they "continued playing" and "had too much fun to stop", showing enjoyment despite rain.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Read: "The restaurant was packed. Every table was occupied, and there was a long wait at the door." What does this suggest?', '[{"label": "A", "text": "The restaurant is unpopular"}, {"label": "B", "text": "The restaurant is popular"}, {"label": "C", "text": "The restaurant is closed"}, {"label": "D", "text": "The restaurant is expensive"}]', 'B', '"Packed", "every table occupied", and "long wait" all indicate the restaurant is popular.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Read: "Sarah studied for three hours. She took the test and failed." What is the main idea?', '[{"label": "A", "text": "Sarah is smart"}, {"label": "B", "text": "Studying doesn''t always guarantee success"}, {"label": "C", "text": "Sarah didn''t study enough"}, {"label": "D", "text": "The test was easy"}]', 'B', 'Despite studying for three hours, Sarah failed, showing effort doesn''t always guarantee success.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Read: "The old man sat alone on the park bench, watching the children play. A smile crossed his face as he remembered his own childhood." What is the man feeling?', '[{"label": "A", "text": "Angry"}, {"label": "B", "text": "Nostalgic"}, {"label": "C", "text": "Bored"}, {"label": "D", "text": "Scared"}]', 'B', '"Remembered his own childhood" and "smile" suggest nostalgia (longing for the past).'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Read: "Tom and Jerry are neighbors. Tom plays guitar every night until midnight. Jerry has to wake up at 5 AM for work." What problem might arise?', '[{"label": "A", "text": "They will become friends"}, {"label": "B", "text": "Jerry might be disturbed by the noise"}, {"label": "C", "text": "Tom will stop playing guitar"}, {"label": "D", "text": "Jerry will move away"}]', 'B', 'Tom''s late-night guitar playing could disturb Jerry, who needs to wake up early.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Read: "The company announced that it would lay off 500 employees due to financial difficulties." What is the company''s situation?', '[{"label": "A", "text": "The company is expanding"}, {"label": "B", "text": "The company is facing financial problems"}, {"label": "C", "text": "The company is hiring more workers"}, {"label": "D", "text": "The company is making profits"}]', 'B', '"Financial difficulties" and "lay off employees" indicate the company is facing problems.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Read: "The scientist spent years researching a cure. After countless experiments, she finally succeeded." What does this tell us about the scientist?', '[{"label": "A", "text": "She was lucky"}, {"label": "B", "text": "She was persistent and determined"}, {"label": "C", "text": "She was wealthy"}, {"label": "D", "text": "She was young"}]', 'B', '"Years researching" and "countless experiments" show persistence and determination.');

-- Reading Hard
WITH cat AS (SELECT id FROM categories WHERE slug = 'reading')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Read: "The author''s use of irony in the final chapter subverts the reader''s expectations, revealing a deeper commentary on societal norms." What literary device is being discussed?', '[{"label": "A", "text": "Metaphor"}, {"label": "B", "text": "Irony"}, {"label": "C", "text": "Alliteration"}, {"label": "D", "text": "Simile"}]', 'B', 'The text explicitly mentions "the author''s use of irony" as the literary device.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Read: "While the politician promised reform, his actions spoke louder than his words. He voted against the very changes he advocated." What is the author''s tone?', '[{"label": "A", "text": "Supportive"}, {"label": "B", "text": "Critical"}, {"label": "C", "text": "Neutral"}, {"label": "D", "text": "Enthusiastic"}]', 'B', 'The author points out the contradiction between promises and actions, indicating a critical tone.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Read: "The experiment yielded inconclusive results. The variables were not properly controlled, and the sample size was insufficient." What is the main criticism?', '[{"label": "A", "text": "The experiment was too expensive"}, {"label": "B", "text": "The methodology was flawed"}, {"label": "C", "text": "The scientists were inexperienced"}, {"label": "D", "text": "The hypothesis was wrong"}]', 'B', '"Variables not controlled" and "sample size insufficient" are criticisms of methodology, not results.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Read: "Her prose was characterized by a lyrical quality that elevated mundane subject matter into something approaching poetry." What does this mean?', '[{"label": "A", "text": "Her writing was boring"}, {"label": "B", "text": "Her writing style was poetic and beautiful"}, {"label": "C", "text": "Her writing was too simple"}, {"label": "D", "text": "Her writing was confusing"}]', 'B', '"Lyrical quality" and "approaching poetry" describe beautiful, poetic writing.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Read: "The CEO''s decision to downsize was a calculated risk. While it temporarily increased profits, the long-term effects on employee morale remained uncertain." What is the author suggesting?', '[{"label": "A", "text": "The decision was clearly wrong"}, {"label": "B", "text": "The decision had mixed outcomes"}, {"label": "C", "text": "The decision was universally praised"}, {"label": "D", "text": "The decision was irrelevant"}]', 'B', '"Calculated risk" with short-term profit but uncertain long-term effects suggests mixed outcomes.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Read: "The juxtaposition of wealth and poverty in the novel serves to highlight the social inequalities of the era." What literary technique is described?', '[{"label": "A", "text": "Foreshadowing"}, {"label": "B", "text": "Juxtaposition"}, {"label": "C", "text": "Flashback"}, {"label": "D", "text": "Symbolism"}]', 'B', 'The text explicitly mentions "juxtaposition" as the technique of placing contrasting elements side by side.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Read: "The study''s findings were later replicated by independent researchers, lending credibility to the original hypothesis." What does this mean?', '[{"label": "A", "text": "The original study was wrong"}, {"label": "B", "text": "Other researchers confirmed the results"}, {"label": "C", "text": "The hypothesis was rejected"}, {"label": "D", "text": "The study was never published"}]', 'B', '"Replicated by independent researchers" and "lending credibility" mean other scientists confirmed the results.');

-- ============================================
-- LISTENING QUESTIONS
-- ============================================

-- Listening Easy
WITH cat AS (SELECT id FROM categories WHERE slug = 'listening')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Listen to: "Where is the nearest hospital?" What is the person looking for?', '[{"label": "A", "text": "A school"}, {"label": "B", "text": "A hospital"}, {"label": "C", "text": "A restaurant"}, {"label": "D", "text": "A store"}]', 'B', 'The person is asking about the location of a hospital.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Listen to: "Could I have a cup of coffee, please?" What does the speaker want?', '[{"label": "A", "text": "Tea"}, {"label": "B", "text": "Water"}, {"label": "C", "text": "Coffee"}, {"label": "D", "text": "Juice"}]', 'C', 'The speaker is requesting coffee.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Listen to: "The train leaves at 3 o''clock." When does the train leave?', '[{"label": "A", "text": "2:00"}, {"label": "B", "text": "3:00"}, {"label": "C", "text": "4:00"}, {"label": "D", "text": "5:00"}]', 'B', 'The speaker clearly states the train leaves at 3 o''clock.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Listen to: "Turn left at the next corner." What direction should you go?', '[{"label": "A", "text": "Right"}, {"label": "B", "text": "Left"}, {"label": "C", "text": "Straight"}, {"label": "D", "text": "Back"}]', 'B', 'The instruction is to turn left.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Listen to: "How much does this shirt cost?" What is the person asking about?', '[{"label": "A", "text": "Color"}, {"label": "B", "text": "Size"}, {"label": "C", "text": "Price"}, {"label": "D", "text": "Material"}]', 'C', '"How much" is asking about the price or cost.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Listen to: "I''d like to book a table for two." What does the person want to do?', '[{"label": "A", "text": "Buy a table"}, {"label": "B", "text": "Reserve a table at a restaurant"}, {"label": "C", "text": "Fix a table"}, {"label": "D", "text": "Clean a table"}]', 'B', '"Book a table" means to reserve a table at a restaurant.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Listen to: "What time does the movie start?" When is the person asking about?', '[{"label": "A", "text": "Movie ending"}, {"label": "B", "text": "Movie start time"}, {"label": "C", "text": "Movie price"}, {"label": "D", "text": "Movie location"}]', 'B', 'The person is asking about when the movie begins.');

-- Listening Medium
WITH cat AS (SELECT id FROM categories WHERE slug = 'listening')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Listen to: "I was going to call you, but my phone died." What prevented the person from calling?', '[{"label": "A", "text": "They forgot"}, {"label": "B", "text": "They were busy"}, {"label": "C", "text": "Their phone had no battery"}, {"label": "D", "text": "They didn''t want to"}]', 'C', '"Phone died" means the phone ran out of battery power.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Listen to: "If I had known about the meeting, I would have attended." What does this mean?', '[{"label": "A", "text": "The person attended the meeting"}, {"label": "B", "text": "The person did not attend the meeting"}, {"label": "C", "text": "The person will attend the meeting"}, {"label": "D", "text": "The person hated the meeting"}]', 'B', 'This is a third conditional expressing regret about a past action that didn''t happen.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Listen to: "The restaurant was so crowded that we had to wait an hour." What happened?', '[{"label": "A", "text": "They ate immediately"}, {"label": "B", "text": "They left the restaurant"}, {"label": "C", "text": "They waited for a table"}, {"label": "D", "text": "They reserved a table"}]', 'C', '"So crowded... had to wait" means they waited because there were no available tables.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Listen to: "I''m looking for a job that offers flexible hours." What is important to the speaker?', '[{"label": "A", "text": "High salary"}, {"label": "B", "text": "Flexible schedule"}, {"label": "C", "text": "Good location"}, {"label": "D", "text": "Big company"}]', 'B', '"Flexible hours" means a schedule that can be adjusted.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Listen to: "The flight has been delayed due to bad weather." Why is the flight delayed?', '[{"label": "A", "text": "Technical problems"}, {"label": "B", "text": "Bad weather"}, {"label": "C", "text": "Staff shortage"}, {"label": "D", "text": "Passenger issues"}]', 'B', 'The speaker explicitly states "due to bad weather" as the reason.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Listen to: "I would rather take the bus than drive in this traffic." What does the speaker prefer?', '[{"label": "A", "text": "Driving"}, {"label": "B", "text": "Taking the bus"}, {"label": "C", "text": "Walking"}, {"label": "D", "text": "Cycling"}]', 'B', '"Would rather... than" shows preference for taking the bus over driving.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Listen to: "The project is due next Friday, so we need to work overtime." What does this mean?', '[{"label": "A", "text": "The project is finished"}, {"label": "B", "text": "The deadline is approaching"}, {"label": "C", "text": "They have plenty of time"}, {"label": "D", "text": "They can take a break"}]', 'B', '"Due next Friday" means the deadline is approaching, requiring extra work.');

-- Listening Hard
WITH cat AS (SELECT id FROM categories WHERE slug = 'listening')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Listen to: "The company''s profits have been declining for three consecutive quarters. Unless they implement major changes, bankruptcy is inevitable." What is the company''s situation?', '[{"label": "A", "text": "The company is thriving"}, {"label": "B", "text": "The company faces serious financial trouble"}, {"label": "C", "text": "The company is expanding"}, {"label": "D", "text": "The company is hiring"}]', 'B', '"Declining profits" and "bankruptcy is inevitable" indicate serious financial trouble.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Listen to: "The diplomat negotiated a ceasefire after months of conflict. Both sides agreed to the terms, bringing temporary peace to the region." What was achieved?', '[{"label": "A", "text": "A permanent peace treaty"}, {"label": "B", "text": "A temporary stop to fighting"}, {"label": "C", "text": "A trade agreement"}, {"label": "D", "text": "A military alliance"}]', 'B', '"Ceasefire" means a temporary stop to fighting. "Temporary peace" confirms this.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Listen to: "The scientist''s theory was initially met with skepticism, but subsequent research validated her findings." How was the theory received?', '[{"label": "A", "text": "Immediately accepted"}, {"label": "B", "text": "First doubted, then proven correct"}, {"label": "C", "text": "Rejected permanently"}, {"label": "D", "text": "Ignored by everyone"}]', 'B', '"Initially met with skepticism" means first doubted; "validated her findings" means proven correct.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Listen to: "The CEO stepped down amid allegations of financial misconduct. The board has appointed an interim successor." What happened to the CEO?', '[{"label": "A", "text": "They were promoted"}, {"label": "B", "text": "They resigned due to scandal"}, {"label": "C", "text": "They retired happily"}, {"label": "D", "text": "They were re-elected"}]', 'B', '"Stepped down amid allegations" means resigned due to accusations of wrongdoing.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Listen to: "The novel''s protagonist undergoes a transformation from a naive youth to a wise adult, symbolizing the journey of self-discovery." What is the story about?', '[{"label": "A", "text": "A war story"}, {"label": "B", "text": "Personal growth and maturity"}, {"label": "C", "text": "A love story"}, {"label": "D", "text": "A mystery"}]', 'B', '"Transformation from naive to wise" and "self-discovery" describe personal growth.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Listen to: "The experiment yielded counterintuitive results. Rather than confirming the hypothesis, the data suggested an entirely new framework." What happened?', '[{"label": "A", "text": "The hypothesis was confirmed"}, {"label": "B", "text": "The results contradicted expectations"}, {"label": "C", "text": "The experiment failed"}, {"label": "D", "text": "No data was collected"}]', 'B', '"Counterintuitive" means contrary to what is expected. The results didn''t confirm the hypothesis.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Listen to: "The politician''s rhetoric was carefully crafted to appeal to undecided voters, employing a balance of emotional appeals and factual arguments." What strategy was used?', '[{"label": "A", "text": "Aggressive campaigning"}, {"label": "B", "text": "Balanced persuasion"}, {"label": "C", "text": "Negative advertising"}, {"label": "D", "text": "Ignoring opponents"}]', 'B', '"Balance of emotional appeals and factual arguments" describes balanced persuasion.');

-- ============================================
-- SPEAKING QUESTIONS
-- ============================================

-- Speaking Easy
WITH cat AS (SELECT id FROM categories WHERE slug = 'speaking')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'What is the polite way to ask for something?', '[{"label": "A", "text": "Give me that!"}, {"label": "B", "text": "I want that!"}, {"label": "C", "text": "Could I please have that?"}, {"label": "D", "text": "Hand it over!"}]', 'C', '"Could I please have that?" is a polite request form.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'How do you introduce yourself?', '[{"label": "A", "text": "I am name John."}, {"label": "B", "text": "My name is John."}, {"label": "C", "text": "John I am."}, {"label": "D", "text": "Name John."}]', 'B', '"My name is [name]" is the correct way to introduce yourself.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'What do you say when someone helps you?', '[{"label": "A", "text": "Nothing"}, {"label": "B", "text": "OK"}, {"label": "C", "text": "Thank you"}, {"label": "D", "text": "Good"}]', 'C', '"Thank you" is the appropriate response when someone helps you.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'How do you ask someone''s name?', '[{"label": "A", "text": "You are who?"}, {"label": "B", "text": "What is your name?"}, {"label": "C", "text": "Name yours?"}, {"label": "D", "text": "Who you?"}]', 'B', '"What is your name?" is the standard way to ask someone''s name.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'How do you say hello politely?', '[{"label": "A", "text": "Hey!"}, {"label": "B", "text": "Yo!"}, {"label": "C", "text": "Good morning/afternoon/evening"}, {"label": "D", "text": "What''s up?"}]', 'C', '"Good morning/afternoon/evening" is a formal, polite greeting.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'What is the polite way to say "no" to a request?', '[{"label": "A", "text": "No!"}, {"label": "B", "text": "Never!"}, {"label": "C", "text": "I''m sorry, I can''t"}, {"label": "D", "text": "Not possible"}]', 'C', '"I''m sorry, I can''t" is a polite way to decline a request.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'How do you ask for directions?', '[{"label": "A", "text": "Tell me where to go!"}, {"label": "B", "text": "Where is the station?"}, {"label": "C", "text": "Give me directions!"}, {"label": "D", "text": "Station where?"}]', 'B', '"Where is [place]?" is the correct way to ask for directions.');

-- Speaking Medium
WITH cat AS (SELECT id FROM categories WHERE slug = 'speaking')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What does "break a leg" mean?', '[{"label": "A", "text": "Get injured"}, {"label": "B", "text": "Good luck"}, {"label": "C", "text": "Run fast"}, {"label": "D", "text": "Be careful"}]', 'B', '"Break a leg" is an idiom meaning "good luck", especially before a performance.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which phrase is used to disagree politely?', '[{"label": "A", "text": "You''re wrong!"}, {"label": "B", "text": "I see your point, but I disagree"}, {"label": "C", "text": "That''s stupid!"}, {"label": "D", "text": "No way!"}]', 'B', '"I see your point, but I disagree" acknowledges the other person while expressing disagreement.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What does "hang in there" mean?', '[{"label": "A", "text": "Wait at the door"}, {"label": "B", "text": "Don''t give up"}, {"label": "C", "text": "Climb something"}, {"label": "D", "text": "Stay still"}]', 'B', '"Hang in there" is an encouraging phrase meaning "don''t give up".'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'How do you ask for clarification politely?', '[{"label": "A", "text": "What?"}, {"label": "B", "text": "Say that again!"}, {"label": "C", "text": "Could you repeat that, please?"}, {"label": "D", "text": "I don''t understand you."}]', 'C', '"Could you repeat that, please?" is a polite way to ask someone to say something again.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What does "piece of cake" mean?', '[{"label": "A", "text": "Something delicious"}, {"label": "B", "text": "Something easy"}, {"label": "C", "text": "Something expensive"}, {"label": "D", "text": "Something difficult"}]', 'B', '"Piece of cake" is an idiom meaning something is very easy.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which phrase is used to make a suggestion?', '[{"label": "A", "text": "You must do this!"}, {"label": "B", "text": "Why don''t we try...?"}, {"label": "C", "text": "Do it now!"}, {"label": "D", "text": "I command you to..."}]', 'B', '"Why don''t we try...?" is a polite way to make a suggestion.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What does "hit the nail on the head" mean?', '[{"label": "A", "text": "Do construction work"}, {"label": "B", "text": "Be exactly right"}, {"label": "C", "text": "Make a mistake"}, {"label": "D", "text": "Hurt yourself"}]', 'B', '"Hit the nail on the head" means to be exactly right about something.');

-- Speaking Hard
WITH cat AS (SELECT id FROM categories WHERE slug = 'speaking')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What does "beat around the bush" mean?', '[{"label": "A", "text": "Hit a bush"}, {"label": "B", "text": "Avoid talking about the main topic"}, {"label": "C", "text": "Run in circles"}, {"label": "D", "text": "Search for something"}]', 'B', '"Beat around the bush" means to avoid getting to the main point.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Which phrase expresses strong agreement?', '[{"label": "A", "text": "I guess so"}, {"label": "B", "text": "I couldn''t agree more"}, {"label": "C", "text": "Maybe"}, {"label": "D", "text": "Possibly"}]', 'B', '"I couldn''t agree more" means you completely agree with the statement.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What does "the ball is in your court" mean?', '[{"label": "A", "text": "Play tennis"}, {"label": "B", "text": "It''s your turn to make a decision"}, {"label": "C", "text": "Go to the gym"}, {"label": "D", "text": "Start a game"}]', 'B', '"The ball is in your court" means it''s your turn to take action or decide.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Which phrase is used to express regret?', '[{"label": "A", "text": "I''m so happy!"}, {"label": "B", "text": "If only I had known"}, {"label": "C", "text": "Great job!"}, {"label": "D", "text": "No problem!"}]', 'B', '"If only I had known" expresses regret about a past situation.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What does "under the weather" mean?', '[{"label": "A", "text": "Outside in the rain"}, {"label": "B", "text": "Feeling sick"}, {"label": "C", "text": "Under a cloud"}, {"label": "D", "text": "In bad weather"}]', 'B', '"Under the weather" is an idiom meaning feeling ill or sick.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Which phrase is used to change the subject politely?', '[{"label": "A", "text": "Shut up!"}, {"label": "B", "text": "Speaking of which..."}, {"label": "C", "text": "That''s boring!"}, {"label": "D", "text": "Who cares?"}]', 'B', '"Speaking of which..." is a polite way to transition to a related topic.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What does "bite the bullet" mean?', '[{"label": "A", "text": "Eat something hard"}, {"label": "B", "text": "Face a difficult situation with courage"}, {"label": "C", "text": "Get hurt"}, {"label": "D", "text": "Fight someone"}]', 'B', '"Bite the bullet" means to endure a painful or difficult situation bravely.');

-- ============================================
-- WRITING QUESTIONS
-- ============================================

-- Writing Easy
WITH cat AS (SELECT id FROM categories WHERE slug = 'writing')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Which sentence has correct punctuation?', '[{"label": "A", "text": "where are you going"}, {"label": "B", "text": "Where are you going?"}, {"label": "C", "text": "Where are you going."}, {"label": "D", "text": "where are you going?"}]', 'B', 'Questions must start with a capital letter and end with a question mark.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'What is a complete sentence?', '[{"label": "A", "text": "Running fast."}, {"label": "B", "text": "The dog runs."}, {"label": "C", "text": "In the park."}, {"label": "D", "text": "Very happy."}]', 'B', 'A complete sentence needs a subject and a verb. "The dog runs" has both.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Which word should be capitalized?', '[{"label": "A", "text": "the eiffel tower"}, {"label": "B", "text": "The Eiffel Tower"}, {"label": "C", "text": "THE EIFFEL TOWER"}, {"label": "D", "text": "the Eiffel tower"}]', 'B', 'Proper nouns (names of specific places) should be capitalized.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Where does a period go?', '[{"label": "A", "text": "At the beginning of a sentence"}, {"label": "B", "text": "In the middle of a sentence"}, {"label": "C", "text": "At the end of a statement"}, {"label": "D", "text": "Before a question"}]', 'C', 'A period (.) is used at the end of declarative sentences (statements).'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Which sentence uses "its" correctly?', '[{"label": "A", "text": "The dog wagged it''s tail."}, {"label": "B", "text": "The dog wagged its tail."}, {"label": "C", "text": "The dog wagged its'' tail."}, {"label": "D", "text": "The dog wagged it self tail."}]', 'B', '"Its" (no apostrophe) shows possession. "It''s" means "it is".'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'What is a topic sentence?', '[{"label": "A", "text": "The first sentence of a paragraph"}, {"label": "B", "text": "A sentence with a question"}, {"label": "C", "text": "A very long sentence"}, {"label": "D", "text": "The last sentence of a paragraph"}]', 'A', 'A topic sentence introduces the main idea of a paragraph and is usually the first sentence.'),
  ((SELECT id FROM cat), 'easy', 'multiple_choice', 'Which sentence uses a comma correctly?', '[{"label": "A", "text": "I like cats dogs and birds."}, {"label": "B", "text": "I like cats, dogs, and birds."}, {"label": "C", "text": "I like cats. dogs. and birds."}, {"label": "D", "text": "I like cats: dogs: and birds."}]', 'B', 'Commas are used to separate items in a list: "cats, dogs, and birds".');

-- Writing Medium
WITH cat AS (SELECT id FROM categories WHERE slug = 'writing')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What is the difference between formal and informal writing?', '[{"label": "A", "text": "Formal uses contractions, informal doesn''t"}, {"label": "B", "text": "Formal avoids contractions and slang, informal uses them"}, {"label": "C", "text": "There is no difference"}, {"label": "D", "text": "Informal is always wrong"}]', 'B', 'Formal writing avoids contractions and slang; informal writing uses them.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which sentence has correct subject-verb agreement?', '[{"label": "A", "text": "The group of students are studying."}, {"label": "B", "text": "The group of students is studying."}, {"label": "C", "text": "The group of students were studying."}, {"label": "D", "text": "The group of students have studying."}]', 'B', '"Group" is a collective noun taking a singular verb: "The group is studying".'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What is a thesis statement?', '[{"label": "A", "text": "A question at the end of an essay"}, {"label": "B", "text": "The main argument or claim of an essay"}, {"label": "C", "text": "A quote from someone else"}, {"label": "D", "text": "A conclusion paragraph"}]', 'B', 'A thesis statement presents the main argument or claim of an essay.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which transition word shows contrast?', '[{"label": "A", "text": "Furthermore"}, {"label": "B", "text": "However"}, {"label": "C", "text": "Therefore"}, {"label": "D", "text": "Additionally"}]', 'B', '"However" shows contrast or contradiction between ideas.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What is a run-on sentence?', '[{"label": "A", "text": "A sentence that is too short"}, {"label": "B", "text": "Two sentences joined without proper punctuation"}, {"label": "C", "text": "A sentence with too many commas"}, {"label": "D", "text": "A sentence that runs away"}]', 'B', 'A run-on sentence occurs when two independent clauses are joined without proper punctuation.'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'Which sentence uses active voice?', '[{"label": "A", "text": "The cake was baked by Mary."}, {"label": "B", "text": "The cake has been baked."}, {"label": "C", "text": "Mary baked the cake."}, {"label": "D", "text": "The cake is being baked."}]', 'C', 'Active voice has the subject performing the action: "Mary (subject) baked (verb) the cake".'),
  ((SELECT id FROM cat), 'medium', 'multiple_choice', 'What is the purpose of a concluding paragraph?', '[{"label": "A", "text": "To introduce new ideas"}, {"label": "B", "text": "To summarize and restate the thesis"}, {"label": "C", "text": "To ask questions"}, {"label": "D", "text": "To provide background information"}]', 'B', 'A concluding paragraph summarizes main points and restates the thesis in different words.');

-- Writing Hard
WITH cat AS (SELECT id FROM categories WHERE slug = 'writing')
INSERT INTO questions (category_id, difficulty, type, question, options, correct_answer, explanation) VALUES
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Which sentence uses a semicolon correctly?', '[{"label": "A", "text": "I love coffee; and tea."}, {"label": "B", "text": "I love coffee; tea is my favorite."}, {"label": "C", "text": "I love coffee; because it wakes me up."}, {"label": "D", "text": "I love coffee; however, I prefer tea."}]', 'D', 'A semicolon connects independent clauses. "However" is a conjunctive adverb, requiring semicolon before and comma after.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What is an oxymoron?', '[{"label": "A", "text": "A very long word"}, {"label": "B", "text": "Two contradictory terms used together"}, {"label": "C", "text": "A repeated word for emphasis"}, {"label": "D", "text": "A word that sounds like its meaning"}]', 'B', 'An oxymoron combines contradictory terms: "deafening silence", "bittersweet".'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Which sentence has correct parallel structure?', '[{"label": "A", "text": "She likes swimming, to run, and cycling."}, {"label": "B", "text": "She likes to swim, running, and cycling."}, {"label": "C", "text": "She likes swimming, running, and cycling."}, {"label": "D", "text": "She likes swim, run, and cycle."}]', 'C', 'Parallel structure requires items in a list to be in the same grammatical form (all gerunds: -ing).'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What is the difference between "affect" and "effect"?', '[{"label": "A", "text": "They mean the same thing"}, {"label": "B", "text": "Affect is usually a verb, effect is usually a noun"}, {"label": "C", "text": "Affect is a noun, effect is a verb"}, {"label": "D", "text": "Affect means to influence, effect means the result"}]', 'B', '"Affect" is typically a verb (to influence); "effect" is typically a noun (a result).'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What is a dangling modifier?', '[{"label": "A", "text": "A modifier that hangs at the end of a sentence"}, {"label": "B", "text": "A modifier that doesn''t clearly modify the intended word"}, {"label": "C", "text": "A very long modifier"}, {"label": "D", "text": "A modifier with too many words"}]', 'B', 'A dangling modifier doesn''t clearly modify the intended word, creating confusion.'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'Which sentence uses an em dash correctly?', '[{"label": "A", "text": "I need -- bread, milk, and eggs."}, {"label": "B", "text": "I need bread -- milk, and eggs."}, {"label": "C", "text": "I need bread, milk -- and eggs."}, {"label": "D", "text": "I need bread, milk, and eggs --."}]', 'A', 'An em dash can introduce a list or explanation: "I need -- bread, milk, and eggs."'),
  ((SELECT id FROM cat), 'hard', 'multiple_choice', 'What is the purpose of a hook in an essay?', '[{"label": "A", "text": "To conclude the essay"}, {"label": "B", "text": "To grab the reader''s attention at the beginning"}, {"label": "C", "text": "To provide citations"}, {"label": "D", "text": "To summarize the main points"}]', 'B', 'A hook is an opening statement that grabs the reader''s attention at the beginning of an essay.');
